export {
  CITIES,
  COMPETENCIES,
  RANKS,
  RESOURCE_IDS,
  type Answer,
  type City,
  type Competency,
  type CompetencySummary,
  type Difficulty,
  type GamePhase,
  type GameState,
  type Question,
  type QuestionMetadata,
  type QuestionOutcome,
  type QuestionPack,
  type QuestionResult,
  type Rank,
  type Resource,
  type ResourceChange,
  type ResourceSnapshot,
  type ResourceValues,
  type Run,
  type RunEndReason,
  type RunSummary,
  type SelectionResult,
  type TimerState,
} from './domain';
